name: agnpy-tutorial

channels:
  - anaconda
  - conda-forge
  - sherpa
  - andreatramacere
  - astropy

dependencies:
  - python=3.9
  - numpy
  - scipy
  - astropy
  - matplotlib
  - iminuit
  - gammapy=1.0
  - swig
  - pip
  - pip:
    - agnpy==0.4.0
    - git+https://github.com/andreatramacere/jetset.git@1.2.2