name: agnpy-tutorial

channels:
  - anaconda
  - conda-forge
  - sherpa
  - andreatramacere
  - astropy

dependencies:
  - python=3.9
  - numpy=1.23
  - scipy=1.9.1
  - matplotlib=3.6.2
  - astropy=5.1
  - iminuit=2.17
  - gammapy=1.0
  - sherpa=4.15.0
  - ipython
  - jupyter
  - pip
  - jetset
  - pip:
    - agnpy
